"""initial_create_all_tables

Revision ID: cb5a26dbb18c
Revises: 
Create Date: 2026-03-29 19:22:37.508779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb5a26dbb18c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('event_name', sa.String(length=50), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('client_ts', sa.BigInteger(), nullable=False),
    sa.Column('server_ts', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analytics_event', 'analytics_events', ['event_name', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_analytics_player', 'analytics_events', ['player_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('content_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('content_id', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_content_type', 'content_versions', ['content_type', 'content_id'], unique=False, postgresql_where=sa.text('is_active = TRUE'))
    op.create_table('players',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=10), nullable=False),
    sa.Column('client_version', sa.String(length=20), nullable=False),
    sa.Column('google_play_id', sa.String(length=255), nullable=True),
    sa.Column('apple_gc_id', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("platform IN ('android', 'ios')", name='ck_players_platform'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apple_gc_id'),
    sa.UniqueConstraint('device_id'),
    sa.UniqueConstraint('google_play_id')
    )
    op.create_index('idx_players_device_id', 'players', ['device_id'], unique=False)
    op.create_table('player_saves',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('save_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('save_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id')
    )
    op.create_index('idx_player_saves_player', 'player_saves', ['player_id'], unique=False)
    op.create_index('idx_saves_fragments', 'player_saves', [sa.literal_column("(save_data->>'totalFragments')")], unique=False)
    op.create_index('idx_saves_lives', 'player_saves', [sa.literal_column("(save_data->>'currentLives')")], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('replaced_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['refresh_tokens.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('idx_refresh_tokens_hash', 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index('idx_refresh_tokens_player', 'refresh_tokens', ['player_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('previous_bal', sa.Integer(), nullable=False),
    sa.Column('new_bal', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('earn', 'spend')", name='ck_transactions_type'),
    sa.CheckConstraint('amount > 0', name='ck_transactions_amount_positive'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transactions_idempotency', 'transactions', ['idempotency_key'], unique=False, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.create_index('idx_transactions_player', 'transactions', ['player_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transactions_player', table_name='transactions')
    op.drop_index('idx_transactions_idempotency', table_name='transactions', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_table('transactions')
    op.drop_index('idx_refresh_tokens_player', table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_hash', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('idx_saves_lives', table_name='player_saves')
    op.drop_index('idx_saves_fragments', table_name='player_saves')
    op.drop_index('idx_player_saves_player', table_name='player_saves')
    op.drop_table('player_saves')
    op.drop_index('idx_players_device_id', table_name='players')
    op.drop_table('players')
    op.drop_index('idx_content_type', table_name='content_versions', postgresql_where=sa.text('is_active = TRUE'))
    op.drop_table('content_versions')
    op.drop_index('idx_analytics_player', table_name='analytics_events')
    op.drop_index('idx_analytics_event', table_name='analytics_events')
    op.drop_table('analytics_events')
    # ### end Alembic commands ###
